TrainingInstitutions/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^teach/', include('teach.urls', namespace='teach')),
    url(r'^stu/', include('stu.urls', namespace='stu')),
]

stu/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    
]

teach/urls.py
from django.conf.urls import url
from django.contrib import admin
from teach import views


urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^emp/$', views.get_emp, name='emp'),
    url(r'^teachers/$', views.get_teachers, name='teachers'),
    url(r'^subjects/$', views.get_subjects, name='subjects'),
    url(r'^search/$', views.Search.as_view(), name='search'),
    # url(r'^search/$', views.search, name='search'),
    url(r'^detail/$', views.Detail.as_view(), name='detail'),  # (?P<id>\d+)
    url(r'^jsontest/$', views.jsontest),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'emp/(\d)/$', views.get_single_emp),
]

teach/models.py
from django.db import models


class LogicDeleteManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_delete=False)


class NoDeleteModel(models.Model):
    is_delete = models.BooleanField(default=False)
    objects = LogicDeleteManager()

    class Meta:
        abstract = True


class Education(NoDeleteModel):
    name = models.CharField(max_length=32, null=False)


class Departments(NoDeleteModel):
    name = models.CharField(max_length=32, null=False)


class Employees(NoDeleteModel):
    name = models.CharField(max_length=32, null=False)
    card_id = models.CharField(max_length=32, unique=True, null=False)
    male = models.BooleanField(null=False)
    birth = models.DateField(null=False, default='2020-01-01')
    education = models.ForeignKey(Education)
    telephone = models.CharField(max_length=16, null=False)
    address = models.CharField(max_length=256)


# many to many relation ? how ?
class Managers(NoDeleteModel):
    emp = models.ForeignKey(Employees)
    department = models.ForeignKey(Departments)


class Salesmen(NoDeleteModel):
    emp = models.ForeignKey(Employees)


class Subjects(NoDeleteModel):
    name = models.CharField(max_length=32, null=False)


class Teachers(NoDeleteModel):
    emp = models.ForeignKey(Employees)
    subject = models.ForeignKey(Subjects)


class Guests(models.Model):
    username = models.CharField(max_length=32, null=False)
    password = models.CharField(max_length=128, null=False)
    datetime = models.DateTimeField()
    star_teacher = models.ManyToManyField(Teachers)

teach/views.py
import base64
import logging
from datetime import datetime

from django.contrib.auth.hashers import make_password, check_password
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q, F
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView

from teach.models import *


logging.basicConfig(level=logging.DEBUG)


# def check_is_login():
#     def wraper(fn):
#         fn.is_login = True
#         return fn
#     return wraper

def check_is_login(dc):
    name = dc['request'].COOKIES.get('my_cookie_key', '')
    name = base64.standard_b64decode(name.encode('utf-8')).decode('utf-8')
    if name == 'abc':
        dc['is_login'] = True
    else:
        dc['is_login'] = False
    return dc


# @check_is_login
def get_teachers(request):
    title = 'Teacher'
    teachers = Teachers.objects.all()
    # teachers = Teachers.objects.filter(emp__name='peipei')
    if teachers.exists():
        return render(request, 'teach/teacher.html', context=check_is_login(locals()))
    else:
        return HttpResponseRedirect(reverse('teach:emp'))


def get_subjects(request):
    subjects = Subjects.objects.all()
    # subjects = Subjects.objects.filter(name='abc')
    if subjects.exists():
        return render(request, 'teach/subjects.html', context=check_is_login(locals()))
    else:
        return HttpResponseRedirect(reverse('teach:emp'))


def get_emp(request):
    title = 'Employees'
    try:
        count_per_page = int(request.GET.get('n', 5))
        if not 1 < count_per_page <= 10:
            count_per_page = 5
    except ValueError:
        count_per_page = 5

    print('count_per_page: %d' % count_per_page)

    paginator = Paginator(Employees.objects.all(), count_per_page)
    try:
        p = int(request.GET.get('p', 1))
        if not 0 < p <= paginator.num_pages:
            raise EmptyPage
    except (ValueError, EmptyPage):
        return render(request, '404.html')

    page = paginator.page(p)
    return render(request, 'teach/emp.html', context=check_is_login(locals()))


def index(request):
    title = 'Home'
    msg = 'Hello!'
    return render(request, 'index.html', check_is_login(locals()))


def search(request):
    title = 'Search'
    msg = ''
    if request.method == 'GET':
        pass

    elif request.method == 'POST':
        wd = request.POST['wd']
        if wd == '':
            msg += 'search content can not be null'
        else:
            msg = request.POST.dict

    return render(request, 'teach/search.html', context=check_is_login(locals()))


class Search(ListView):
    model = Managers
    # allow_empty = True
    template_name = 'teach/search.html'
    # paginate_by = 2

    # can show all if no this 'get()', but can not search
    def get(self, request, *args, **kwargs):
        wd = request.GET.get('wd', '')
        print(wd)
        if wd != '':
            emp = Employees.objects.filter(name__contains=wd)
            ids = []
            print('********** 2')
            if emp.exists():
                for i in emp:
                    ids.append(i.id)
            self.queryset = self.model.objects.filter(emp_id__in=ids)
        else:
            self.queryset = self.model.objects.all()
        return super().get(request, args, kwargs)


class Detail(DetailView):
    id = None
    model = Employees
    pk_url_kwarg = 'id'
    template_name = 'teach/detail.html'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['id'] = 2
    #     return context

    def get(self, request, *args, **kwargs):
        pk = int(request.GET.get('id'))
        if pk:
            kwargs['id'] = pk
            print('\n**********************************')
            print(kwargs)
            return super().get(request, *args, **kwargs)
        else:
            return render(request, '404.html')


def jsontest(request):
    title = 'JsonTest'
    msg = ''
    if request.method == 'GET':
        return render(request, 'teach/jsontest.html', context=check_is_login(locals()))

    elif request.method == 'POST':
        response = JsonResponse(request.POST.dict(), content_type='application/json')
        return response


MY_HEX_SALT = r'adsfljf465asdf aeq&((*fasdf321wq#@&<>?'


def login(request):
    data = {'title': 'Login'}

    if request.method == 'POST':
        name, pw, cf = get_user_and_pw(request.POST.dict())
        if name != '' and pw != '':
            if Guests.objects.filter(username=name).exists():
                guest = Guests.objects.first()
                if check_password(pw, guest.password):  # login success!
                    data['msg'] = 'Welcome Back, %s!' % name
                    data['is_login'] = True

                    guest.datetime = datetime.now()
                    guest.save()

                    logging.info(data)

                    rsp = render(request, 'index.html', context=data)
                    name = base64.standard_b64encode(name.encode('utf-8')).decode('utf-8')
                    rsp.set_cookie('my_cookie_key', name)
                    return rsp

            data['msg'] = 'Wrong Account or Password'
        else:
            data['msg'] = 'Wrong Input, unexpect empty! '

        return render(request, 'teach/login.html', data)

    elif request.method == 'GET':
        return render(request, 'teach/login.html', data)


def register(request):
    data = {'title': 'Register'}
    msg = ''

    if request.method == 'POST':
        name, pw, cf = get_user_and_pw(request.POST.dict())
        if name != '' and pw != '' and pw == cf:
            if not Guests.objects.filter(username=name).exists():
                guest = Guests()
                guest.username = name
                guest.password = make_password(pw, MY_HEX_SALT)
                guest.datetime = datetime.now()
                guest.save()

                data['msg'] = 'Congratulations!'
                return render(request, 'index.html', context=data)
            else:
                msg = 'This Account Name Has been Registered, please change another!'
        else:
            if name == '' or pw == '':
                msg = 'Wrong Input, unexpect empty! '
            else:
                msg = 'Two input password must be consistent'

        data['msg'] = msg
        return render(request, 'teach/register.html', data)

    elif request.method == 'GET':
        return render(request, 'teach/register.html', data)


def get_user_and_pw(dc: dict) -> tuple:
    name = dc.get('username', '')
    pw = dc.get('password', '')
    cf = dc.get('confirm', '')
    return name, pw, cf


def personal(request):
    title = 'Personal'
    msg = 'your COOKIE is : '
    for c in request.COOKIES.keys():
        msg += '\n' + c + ' : '
        msg += request.COOKIES[c] + '\n'
    name = request.COOKIES.get('my_cookie_key', '')
    if name != '':
        name = base64.standard_b64decode(name.encode('utf-8')).decode('utf-8')
        guest = Guests.objects.filter(username=name)
        if guest.exists():
            date_time = guest.first().datetime
    rsp = render(request, 'teach/personal.html', check_is_login(locals()))
    return rsp


def logout(request):
    title = 'Login'
    rsp = render(request, 'teach/login.html', locals())
    rsp.delete_cookie('my_cookie_key')
    return rsp


def get_single_emp(request, number):
    number = int(number)
    if 0 < number <= Employees.objects.count():
        emps = Employees.objects.all().order_by('birth')[number-1:number]

    title = 'Employees'
    return render(request, 'teach/emp.html', context=check_is_login(locals()))

templates/teach/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>



<br>
<br>
<br>
<label style="color:gray"> - - - - - - - - - - - - -      CopyRight @ Cyhol Leung      - - - - - - - - - - - - - </label>

</body>
</html>

templates/teach/emp.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/emp.css' %}">
{% endblock %}

{% block content %}

{#choose count per page#}
    <h3>how many would you like in page ?</h3>
    <a href="{% url 'teach:emp' %}?n=2;p=1">{% ifequal count_per_page 2  %}[2]{% else %}2{% endifequal %}</a>
    <a href="{% url 'teach:emp' %}?n=3;p=1">{% ifequal count_per_page 3  %}[3]{% else %}3{% endifequal %}</a>
    <a href="{% url 'teach:emp' %}?n=5;p=1">{% ifequal count_per_page 5  %}[5]{% else %}5{% endifequal %}</a>
    <a href="{% url 'teach:emp' %}?n=10;p=1">{% ifequal count_per_page 10  %}[10]{% else %}10{% endifequal %}</a>

{#show employees in pages#}
    <h1>Employees</h1>
    <ul>
        {% for emp in page %}
            <li style="font-style: italic">{{ emp.name }}</li>
            <ul>
                <li>card_id:    {{ emp.card_id }}</li>
                <li>gender:     {% if emp.male %}Male{% else %}Female{% endif %}</li>
                <li>TEL:        {{ emp.telephone }}</li>
                <li>address:    {{ emp.address }}</li>
                <li>birthday:   {{ emp.birth }}</li>
                <ul style="child-align: right">
                    {% for teacher in emp.teachers_set.all %}
                        <li>{{ teacher.subject.name }}</li>
                    {% endfor %}

                </ul>

            </ul>
            <br>
        {% endfor %}

    </ul>

    <br>

{#show the page index#}

    {% if page.has_previous %}
        <a style="color: blue" href="{% url 'teach:emp' %}?p={{ page.previous_page_number }};n={{ count_per_page }}">
            &nbsp prev &nbsp
        </a>
    {% else %}
        <a style="color: gray">
            &nbsp prev &nbsp
        </a>
    {% endif %}


    {% for foo in page.paginator.page_range %}
        &nbsp &nbsp
        {% if foo == page.number %}
            <a style="color: red">
                [{{ foo }}]
            </a>
        {% else %}
            <a style="color: blue" href="{% url 'teach:emp' %}?p={{ foo }};n={{ count_per_page }}">
                {{ foo }}
            </a>
        {% endif %}
        &nbsp &nbsp
    {% endfor %}


    {% if page.has_next %}
        <a style="color: blue" href="{% url 'teach:emp' %}?p={{ page.next_page_number }};n={{ count_per_page }}">
            next
        </a>
    {% else %}
        <a style="color: gray">
            next
        </a>
    {% endif %}

{% endblock %}

templates/teach/jsontest.html
{% extends 'base.html' %}

{% block header %}
    <h1>Please input something and press submit</h1>
{% endblock %}

{% block banner %}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>text1: <input type="text" name="text1"></p>
        <p>text2: <input type="text" name="text2"></p>
        <p>text3: <input type="text" name="text3"></p>
        <input type="submit" value="提交">
    </form>
{% endblock %}

</body>
</html>

templates/teach/login.html
{% extends 'base.html' %}

{% block banner %}
<h3>Login page doesn't has a banner</h3>
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    <p>username : <input type="text", name="username"></p>
    <p>password : <input type="password", name="password"></p>
        <input type="submit" value="登录" style="font-size: large">
        <label style="color: red">{{ msg }}</label>

    </form>

    <p>If you do not have Account, please <a href="{% url 'teach:register' %}">注册</a></p>
{% endblock %}

templates/teach/logout.html
{% extends 'base.html' %}

{% block content %}
    <p></p>
    <p></p>
    <p></p>
    <a style="color: red" href="{% url 'teach:login' %}">logout</a>
{% endblock %}

templates/teach/personal.html
{% extends 'base.html' %}

{% block content %}
    <h2>Here is Personal Center</h2>
    <h3>{{ msg }}</h3>
    <p></p>
    <p></p>
    <p></p>
    <p>last visit time : {{ date_time }}</p>
    <a href="{% url 'teach:logout' %}">logout</a>
{% endblock %}

templates/teach/register.html
{% extends 'base.html' %}

{% block header %}
<h2 style="color:red">Please Register</h2>
{% endblock %}

{% block banner %}
{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    <p>username : <input type="text", name="username"></p>
    <p>password : <input type="password", name="password"></p>
    <p>confirm : <input type="password", name="confirm"></p>
        <input type="submit" value="注册" style="font-size: large">
        <label style="color: red">{{ msg }}</label>

    </form>

    <p>If you have Account, please <a href="{% url 'teach:login' %}">登录</a></p>

{% endblock %}

templates/teach/search.html
{% extends 'base.html' %}

{% block content %}

<h1>Please input keyword for searching</h1>
<form method="get" action="{% url 'teach:search' %}">
    {% csrf_token %}
    <p>keyword: <input type="text" name="wd"></p>
    <input type="submit" value="提交">
</form>
    <ul>
        {% for object in object_list %}
            <li>
                <a href="{% url 'teach:detail' %}?id={{ object.emp.id }}">{{ object.emp.name }}</a>
            </li>
        {% endfor %}
    </ul>
{{ msg }}
{% if wd %}
<h1>you input : {{ wd }}</h1>
{% endif %}

{% endblock %}

templates/teach/subjects.html
{% extends 'base.html' %}

{% block content %}
<h1>Subjects</h1>
<ul>
    {% for subject in subjects %}
        <li>{{ subject.name }}</li>
    {% endfor %}

</ul>
{% endblock %}

templates/teach/teacher.html
{% extends 'base.html' %}

{% block content %}

<h1>Teachers</h1>
<ul>
    {% for teacher in teachers %}
        <li style="color:green">{{ teacher.emp.name }}</li>
        {% empty %}
        <li style="color:red">can't find any result!</li>
        <a href="{% url 'teach:emp' %}">show all employees</a>
    {% endfor %}

</ul>
{% endblock %}