TrainingInstitutions/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^teach/', include('teach.urls', namespace='teach')),
    url(r'^stu/', include('stu.urls', namespace='stu')),
]

stu/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    
]

teach/urls.py
from django.conf.urls import url
from django.contrib import admin
from teach import views


urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^emp/$', views.get_emp, name='emp'),
    url(r'^teachers/$', views.get_teachers, name='teachers'),
    url(r'^subjects/$', views.get_subjects, name='subjects'),
    url(r'^search/$', views.Search.as_view(), name='search'),
    # url(r'^search/$', views.search, name='search'),
    url(r'^detail/$', views.Detail.as_view(), name='detail'),  # (?P<id>\d+)
    url(r'^jsontest/$', views.jsontest),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^personal/$', views.personal, name='personal'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'emp/(\d)/$', views.get_single_emp),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <script type="text/javascript">

    </script>

    {% block extJS %}

    {% endblock %}

    {% block extCSS %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endblock %}
</head>
<body>

{% block header %}
<ul style="list-style-type: none; margin: 0; padding: 0; overflow: hidden">
    <li style="float: left">&nbsp <a href="{% url 'teach:index' %}">首页</a> &nbsp</li>
    <li style="float: left">&nbsp <a href="{% url 'teach:teachers' %}">教师风采</a> &nbsp</li>
    <li style="float: left">&nbsp <a href="{% url 'teach:subjects' %}">精选科目</a> &nbsp</li>
    <li style="float: left">&nbsp <a href="{% url 'teach:search' %}">搜索</a> &nbsp</li>
    {% if is_login %}
    <li style="float: left">&nbsp <a href="{% url 'teach:personal' %}">个人中心</a> &nbsp</li>
    {% else %}
    <li style="float: left">&nbsp <a href="{% url 'teach:login' %}">登录</a> &nbsp</li>
    {% endif %}
</ul>
{% endblock %}

{% block banner %}
    <h1>This is a Banner</h1>
{% endblock %}

<br>

{% block content %}

{% endblock %}

<br>

{% block footer %}

{% endblock %}

<br>
<br>
<br>
<label style="color:gray"> - - - - - - - - - - - - -      CopyRight @ Cyhol Leung      - - - - - - - - - - - - - </label>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block banner %}
    <h3>notice the massage below:</h3>
{% endblock %}

{% block content %}
    <h2>{{ msg }}</h2>
{% endblock %}